name: Validate with hassfest

on:
  push:
    branches:
      - master
  schedule:
    - cron: "28 21 7 * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master
