name: 'Lock Threads'

on:
  schedule:
    - cron: '28 20 */3 * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          issue-inactive-days: "7"
          pr-inactive-days: "1"
          issue-lock-reason: ""
